name: Back-end CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: backend

env:
  DJANGO_SETTINGS_MODULE: graditude.config.local
  DOMAIN_NAME: http://localhost:8000
  REDIS_URL: redis://redis:6379/0
  CORS_ORIGIN_WHITELIST: http://localhost:3000
  DATABASE_URL: pgsql://postgres:postgres@localhost:5432/postgres

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('**/local.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt

      - name: Lint and Style (flake8, black)
        run: |
          flake8 --config=setup.cfg
          black .

      - name: Static Type Checking (mypy)
        run: mypy .

      - name: Run Tests (Pytest)
        run: |
          pytest

      - name: Upload Coverage Report (Codecov)
        uses: codecov/codecov-action@v1
        with:
          file: "./backend/coverage.xml"
          flags: backend
          fail_ci_if_error: true
